eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka
  server:
    enable-self-preservation: false

# Uncomment if you'd rather use multi-peer Eureka with the eureka-1 and eureka-2 
# profiles below (see Listing 13.1)

    
---
spring:
  profiles: eureka-1
  application:
    name: eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1.tacocloud.com

other:
  eureka:
    host: eureka2.tacocloud.com
    port: 8762

---
spring:
  profiles: eureka-2
  application:
    name: eureka-2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2.tacocloud.com

other:
  eureka:
    host: eureka1.tacocloud.com
    port: 8761