spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   com.mysql.cj.jdbc.Driver 是 mysql-connector-java 6中的 (用于 MySQL 5.0 以上版本),
    #   需要指定时区 serverTimezone
    url: jdbc:mysql://localhost:3306/tacocloud_mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 220616

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    # create/update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # 方言: MySQL 5.0 以上版本 ↑

server:
  port: 8443
  ssl:
    key-store: classpath:static/mykeys.jks
    key-store-password: TacoCloud
    key-password: TacoCloud

thymeleaf:
  chache: false
  mode: HTML

logging:
  level:
    tacos: WARN