spring:
#  profiles:
#    active: prod

  jpa:
    show-sql: true
    # 显示 SQL 语句
    hibernate:
      ddl-auto: update
      # create/update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # 设置方言


thymeleaf:
  cache: false
  # 禁用缓存
  mode: HTML


server:
  port: 8443
  # 将server.port属性显式设置为0,它会任选一个端口
  ssl: # 浏览器会警告 与此站点的连接不安全
    key-store: classpath:static/mykeys.jks
    # keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA
    # 可以使用 file://URL 或者 classpath:URL ,需要打包成JAR文件时, 使用classpath:
    key-store-password: TacoCloud
    key-password: TacoCloud


logging:
  #path:
  #file:
  level:
    root: INFO
    # logger -> root 的 logging 级别设置为 WARN
    org:springframework:security: DEBUG
    # Spring Security 的日志级别设置为 DEBUG

# 使用特定的属性值:
#greeting:
#  welcome: You are using ${spring.application.name}.


taco:
  orders:
    pageSize: 10
# 配置属性元数据: 在src/main/resource/META-INF下创建自定义配置属性的元数据additional-spring-configuration.json
# Spring Boot 灵活的属性命名功能允许属性名出现不同的变种, taco.orders.page-size = taco.orders.pageSize




# 以上属性是所有 profiles通用的, 如果当前激活 profiles 没有设置以上属性, 以上属性将作为默认值
---
# Spring profiles 条件化配置: (仅适用于 prod profiles)
spring:
  profiles: prod
  # 使用 spring.profiles属性来命名 profile

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql --version 8.0.25
    url: jdbc:mysql://localhost:3306/tacocloud_mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    # mysql --version 8.0.25 (需设置时区)
    username: root
    password: 220616

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # mysql --version 8.0.25

logging:
  level:
    root: WARN


